### ISSUE TITLE
Adding additional metrics to monitor.

### ISSUE THREAD

**Issue by tankalasreekar** [ksdkamesh99/TensorGram#1]
At present, the model is returning only loss function values to telegram and all the metrics are sent after the training has ended. But try adding a feature that allows specifying the quantities to monitor and send the values to the telegram.

PS: Very nice package, awesome. Easily able to monitor the model when away from the system.

**Comment by ksdkamesh99** [comment]
@tankalasreekar 
Very good idea. Will definitely make it done in next release. Thanks for raising the issue. If you like the project please do 🌟 this repo and if you are interested in what things I do please do follow me on github.
