### ISSUE TITLE
Add Contributors. md

### ISSUE THREAD

**Issue by muthuannamalai12** [ksdkamesh99/TensorGram#13]
Hai,
I would like to add Contributors.md file in your project in the form of a table and display a link to it in README.md

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign me this issue.

**Comment by ksdkamesh99** [comment]
You can work on it @muthuannamalai12

**Comment by muthuannamalai12** [comment]
> You can work on it @muthuannamalai12

Thank you

**Comment by muthuannamalai12** [comment]
I have created a pull request.Kindly review it
