### ISSUE TITLE
Integrate welcome bot

### ISSUE THREAD

**Issue by muthuannamalai12** [ksdkamesh99/TensorGram#15]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

If you feel this is a great idea!
Please assign it to me.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by muthuannamalai12** [comment]
> I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
> For reference, check out: https://github.com/apps/welcome
> 
> If you feel this is a great idea!
> Please assign it to me.

I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by ksdkamesh99** [comment]
I am in a plan to do but you asked me the same anyway this issue I will only handle

**Comment by ksdkamesh99** [comment]
Thanks for your issue

**Comment by ksdkamesh99** [comment]
Please focus on other issues

**Comment by ksdkamesh99** [comment]
Before creating a issue please discuss this on discord and share the views

**Comment by muthuannamalai12** [comment]
> Before creating a issue please discuss this on discord and share the views

Ok. I will follow it

**Comment by muthuannamalai12** [comment]
> Please focus on other issues

Ok
