### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by tharunc** [ksdkamesh99/TensorGram#16]
Hello there,
         I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time as a part of DWOC. Please assign me this issue. 
For reference, kindly check out: https://github.com/apps/welcome

THANK YOU

**Comment by ksdkamesh99** [comment]
@tharunc  You can start working. But follow certain things who ever comes and create a issue or pull request for first time then you tell him to star the repo and follow my profile

**Comment by ksdkamesh99** [comment]
@tharunc Please do star this repo and follow my profile.
THank you for visiting the repo 
Happy open source
