### ISSUE TITLE
README FILE BADGES IMPROVE

### ISSUE THREAD

**Issue by akrish4** [ksdkamesh99/TensorGram#18]
Hi @ksdkamesh99 
There are no badges or shields in the readme file , Kindly assign me if you would like to see more badges in it
I would be glad to work on it pls bro

![readme1](https://user-images.githubusercontent.com/61831021/103936213-2af59000-514d-11eb-8591-7cfa00678fb0.PNG)

**Comment by ksdkamesh99** [comment]
Yes you can work on @akrish4
