### ISSUE TITLE
Please give credits to Keras Notify

### ISSUE THREAD

**Issue by ucalyptus** [ksdkamesh99/TensorGram#2]
https://github.com/ucalyptus/keras-notify

Your project has essentially the same features.
So even if you make it independently,  you should provide mention of my project in the README , since it was created much earlier than your first commit.

**Comment by ksdkamesh99** [comment]
Thanks for looking into my project. I request you to please 🌟 my repository.

**Comment by ucalyptus** [comment]
nope, I'll report.

**Comment by ksdkamesh99** [comment]
To whom you will report

**Comment by ksdkamesh99** [comment]
@ucalyptus

**Comment by ksdkamesh99** [comment]
there are many apps like yours

**Comment by ksdkamesh99** [comment]
Ok don't worry I will credit. Just give me 2 days time I will change my readme. Are you happy with this. @ucalyptus

**Comment by ucalyptus** [comment]
@ksdkamesh99 still waiting!
