### ISSUE TITLE
Readme updation with various open-source programs this project is a part of like dwoc

### ISSUE THREAD

**Issue by Sloth-Panda** [ksdkamesh99/TensorGram#22]
Would like to do this if interested plz assign it to me

**Comment by ksdkamesh99** [comment]
Hello @Sloth-Panda You can work on it

**Comment by ksdkamesh99** [comment]
Make sure you star the repo and follow my profile

**Comment by Sloth-Panda** [comment]
Hey @ksdkamesh99  you have closed it so should I still make a pr?

**Comment by ksdkamesh99** [comment]
Please do make conversation in discord
