### ISSUE TITLE
Improvement of readme

### ISSUE THREAD

**Issue by Sloth-Panda** [ksdkamesh99/TensorGram#26]
The readme does not look so nice can be made attractive by adding some gifs and other stuff as required. Let  me know if you want to get this done. Also plz assign the dwoc tag

**Comment by ksdkamesh99** [comment]
Tell what changes you want to perform

**Comment by Sloth-Panda** [comment]
changes that need to be performed->
1. I guess the readme is missing gifs that can make it attractive
2.  towards the end there is a typing error in the readme the license" part that to be fixed
3.  I guess images if left-aligned look better as everything in ur readme is also left alligned

**Comment by ksdkamesh99** [comment]
What GIFs you want to add @Sloth-Panda

**Comment by Sloth-Panda** [comment]
check the discord channel @ksdkamesh99
