### ISSUE TITLE
Contributing file 

### ISSUE THREAD

**Issue by akrish4** [ksdkamesh99/TensorGram#6]
Hi @ksdkamesh99 
I would like to contrintute this project in documentation 
There is a ckntributing.md file missing 
Let me work on this  also kindly assign me this issue

**Comment by ksdkamesh99** [comment]
Definitely you can work on it @akrish4

**Comment by ksdkamesh99** [comment]
Thanks for choosing this project in DevScript Winter of Code. I wish you great success in your open source journey.
Please do fork this project and star this repository. I request you to follow me on GitHub for my future projects.

**Comment by ksdkamesh99** [comment]
@akrish4 I hope it will be completed soon

**Comment by akrish4** [comment]
> @akrish4 I hope it will be completed soon

Hi @ksdkamesh99 
yes 
Thank you

**Comment by akrish4** [comment]
I have worked on it , kindly do check and merge it #12 
Kindly do add the same both labels in the pr also 
@ksdkamesh99

**Comment by akrish4** [comment]
#12

**Comment by ksdkamesh99** [comment]
ok @akrish4 Please do reference your pull request here it self

**Comment by ksdkamesh99** [comment]
I will review it

**Comment by akrish4** [comment]
@ksdkamesh99 Kindly add the same labels added in the issue to the pr also otherwise it won't be counted in dwoc

**Comment by ksdkamesh99** [comment]
I linked it don't worry

**Comment by akrish4** [comment]
> I linked it don't worry

Actually brother , DWOC will check issue and pr so , they need to see the labels , so you have linked it thank you , but kindly pls add the `DWOC` and  `Level-2` labels to pr too

**Comment by ksdkamesh99** [comment]
okk bro
